name: dex_actions_pipeline

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true  # temporary
    container:
      image: us-east1-docker.pkg.dev/dex-apps-prod/xci/xci:v0.7.4
      credentials:
        username: _json_key
        password: ${{ secrets.GCLOUD_ARTIFACT_REGISTRY_PUBLISHER_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check code quality
        run: |-
          xci lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    container:
      image: us-east1-docker.pkg.dev/dex-apps-prod/xci/xci:v0.7.4
      credentials:
        username: _json_key
        password: ${{ secrets.GCLOUD_ARTIFACT_REGISTRY_PUBLISHER_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run unit tests
        run: |-
          xci test

  publish-to-prod:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    container:
      image: us-east1-docker.pkg.dev/dex-apps-prod/xci/xci:v0.7.4
      credentials:
        username: _json_key
        password: ${{ secrets.GCLOUD_ARTIFACT_REGISTRY_PUBLISHER_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: us-east1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCLOUD_ARTIFACT_REGISTRY_PUBLISHER_SERVICE_ACCOUNT_JSON }}
      - name: Publish to Prod
        run: |-
          xci publish